from typing import Protocol

from entities.clip.domain.Clip import Range
from entities.source.domain.Word import Word
from entities.source.domain.Source import Source

class SourceRepository(Protocol):
    def findSourceById(self, sourceId: str) -> (Source | None): ...
    def saveSource(self, source: Source): ...
    def saveTranscription(self, sourceId: str, words: list[Word]): ...
    def getClipWords(self, clipRange: Range, sourceId: str) -> list[Word]: ...
