AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack that deploys an isolated VPC and a private
             Amazon ECS service in that isolated VPC.
Parameters:
  ECRUri:
    Type: String
    Description: The URI of the private container image to deploy
  SourceBucketName:
    Type: String
    Description: The name of the S3 bucket to use for the source code
    Default: "sources-file-bucket"

Resources:

  # The networking configuration. This creates an isolated
  # network specific to this particular environment
  VpcStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc.yml

  AppStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: app.yml
      Parameters:
        ECRUri: !Ref ECRUri 
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt VpcStack.Outputs.PublicSubnetIds
        SourceBucket: !Ref SourceBucketName

  SNSStack:
    Type: AWS::Serverless::Application
    DependsOn: AppStack
    Properties:
      Location: sns.yml
      Parameters:
        ServerUrl: !GetAtt AppStack.Outputs.ServerEndpoint

  # This stack defines the container deployment
  BatchStack:
    Type: AWS::Serverless::Application
    DependsOn: [VpcStack, SNSStack]
    Properties:
      Location: batch.yml
      Parameters:
        ECRUri: !Ref ECRUri
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateSubnetIds: !GetAtt VpcStack.Outputs.PrivateSubnetIds
        PrivateLinkEndpointSecurityGroup: !GetAtt VpcStack.Outputs.PrivateLinkEndpointSecurityGroup
        TopicArn: !GetAtt SNSStack.Outputs.TopicArn

  S3Stack:
    Type : AWS::Serverless::Application
    DependsOn: BatchStack
    Properties:
      Location: source_s3_and_lambda.yml
      Parameters:
        JobQueueArn: !GetAtt BatchStack.Outputs.JobQueueArn
        AfterUploadJobDefinitionArn: !GetAtt BatchStack.Outputs.AfterUploadJobDefinitionArn
        S3BucketName: !Ref SourceBucketName

