AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack that deploys an isolated VPC and a private
             Amazon ECS service in that isolated VPC.
Parameters:
  ECRUri:
    Type: String
    Description: The URI of the private container image to deploy
  SourceBucketName:
    Type: String
    Description: The name of the S3 bucket to use for the source code
    Default: "sources-file-bucket"

Resources:
  VpcStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc.yml

  AppStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: app.yml
      Parameters:
        ECRUri: !Ref ECRUri 
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt VpcStack.Outputs.PublicSubnetIds
        SourceBucket: !Ref SourceBucketName

  S3Stack:
    Type : AWS::Serverless::Application
    Properties:
      Location: source_s3_and_lambda.yml
      Parameters:
        S3BucketName: !Ref SourceBucketName

