from typing import Optional, Protocol

class FileHandler(Protocol):
    def downloadFiles(self, keys: Optional[list[str]]): ...
    def saveFiles(self): ...
    def checkIfFilesExist(self, file: str) -> bool: ...

