from typing import Any, Protocol


class System(Protocol):
    def fileExist(self, path: str) -> bool: ...
    def path(self, path: str) -> str: ...
    def run(self, command: list[str], silent: bool = True) -> tuple[str, str, int]: ...
    def readFile(self, path: str) -> Any: ...
    def rm(self, path: str): ...
    def rename(self, old: str, new: str): ...
    def env(self, key: str) -> (str | None): ...
    def clean(self): ...
