name: Push the Docker image to AWS ECR Repo
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com
  CACHE_TO_META: mode=max,image-manifest=true,oci-mediatypes=true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_URI }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and use a new builder instance
        run: |
          docker buildx create --name mybuilder --use

      - name: Build test stage
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: test-app
          target: test
          builder: mybuilder
          cache-from: type=registry,ref=${{ env.ECR_URI }}/app:test-cache
          cache-to: type=registry,${{ env.CACHE_TO_META }},ref=${{ env.ECR_URI }}/app:test-cache

      - name: Test app
        run: |
          docker run -rm test-app

      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.ECR_URI }}/app:latest
          builder: mybuilder
          cache-from: type=registry,ref=${{ env.ECR_URI }}/app:cache
          cache-to: type=registry,${{ env.CACHE_TO_META }},ref=${{ env.ECR_URI }}/app:cache

      - name: Build and push processor
        uses: docker/build-push-action@v5
        with:
          context: processor
          file: ./processor/Dockerfile
          push: true
          tags: ${{ env.ECR_URI }}/processor:latest
          builder: mybuilder
          cache-from: type=registry,ref=${{ env.ECR_URI }}/processor:cache
          cache-to: type=registry,${{ env.CACHE_TO_META }},ref=${{ env.ECR_URI }}/processor:cache
