name: Deploy the stack to AWS CloudFormation
on:
  workflow_dispatch:

env:
  ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(echo $GITHUB_SHA | cut -c1-7)"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Sam
        run: |
          #sudo apt-get update;
          #sudo apt-get install -y unzip;
          #wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip;
          #sudo unzip aws-sam-cli-linux-x86_64.zip -d sam-installation;
          #sudo ./sam-installation/install;
          sam --version;
      - name: Deploy stack to cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Stack-${{ steps.commit_hash.outputs.hash }}
          template: ./cloudformation/parent.yml
          capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
          parameter-overrides: "ECRUri=${{ env.ECR_URI }}, DatabaseUrl=${{ secrets.DATABASE_URL }}, OpenApiKey=${{ secrets.OPEN_API_KEY }}"
