name: Build app, test it and push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY_URI: ghcr.io/javiermorales9
  USERNAME: javiermorales9
  CACHE_TO_META: mode=max,image-manifest=true,oci-mediatypes=true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN_PUSHING_IMAGES }}

      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and use a new builder instance
        run: |
          docker buildx create --name mybuilder --use

      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY_URI }}/app:production,${{ steps.commit_hash.outputs.hash }}
          builder: mybuilder
          cache-from: type=registry,ref=${{ env.REGISTRY_URI }}/app:cache-staging

      - name: Build and push processor
        uses: docker/build-push-action@v5
        with:
          context: processor
          file: ./processor/Dockerfile
          push: true
          tags: ${{ env.REGISTRY_URI }}/processor:production,${{ steps.commit_hash.outputs.hash }}
          builder: mybuilder
          cache-from: type=registry,ref=${{ env.REGISTRY_URI }}/processor:cache-staging
