name: Push the Docker image to AWS ECR Repo
on:
  workflow_dispatch:
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy stack to cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: isolate-vpc-environment
          template: ./cloudformation/parent.yml
          capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
          parameter-overrides: "ImageUri=${{ steps.build-image.outputs.image }}"
